In [4]:
import numpy as np
import matplotlib.pyplot as plt

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

# XOR truth table
X = np.array([[0, 0],
              [0, 1],
              [1, 0],
              [1, 1]])

# Output labels for XOR
y = np.array([[0], [1], [1], [0]])

# Set random seed for reproducibility
np.random.seed(42)

# Define architecture
input_size = 2
hidden_size = 2
output_size = 1
learning_rate = 0.1
epochs = 10000

# Initialize weights and biases
weights_input_hidden = np.random.rand(input_size, hidden_size)
bias_hidden = np.zeros((1, hidden_size))
weights_hidden_output = np.random.rand(hidden_size, output_size)
bias_output = np.zeros((1, output_size))

# Lists to store mean squared error for each iteration
mse_history = []

# Training the neural network using backpropagation
for epoch in range(epochs):
    # Feedforward
    hidden_layer_input = np.dot(X, weights_input_hidden) + bias_hidden
    hidden_layer_output = sigmoid(hidden_layer_input)
    
    output_layer_input = np.dot(hidden_layer_output, weights_hidden_output) + bias_output
    predicted_output = sigmoid(output_layer_input)

    # Backpropagation
    output_error = y - predicted_output
    output_delta = output_error * sigmoid_derivative(predicted_output)

    hidden_layer_error = output_delta.dot(weights_hidden_output.T)
    hidden_layer_delta = hidden_layer_error * sigmoid_derivative(hidden_layer_output)

    # Update weights and biases
    weights_hidden_output += learning_rate * hidden_layer_output.T.dot(output_delta)
    bias_output += learning_rate * np.sum(output_delta, axis=0, keepdims=True)

    weights_input_hidden += learning_rate * X.T.dot(hidden_layer_delta)
    bias_hidden += learning_rate * np.sum(hidden_layer_delta, axis=0, keepdims=True)



# Display final weights and bias
print("Final Weights (Input to Hidden):")
print(weights_input_hidden)
print("Final Bias (Hidden):")
print(bias_hidden)
print("Final Weights (Hidden to Output):")
print(weights_hidden_output)
print("Final Bias (Output):")
print(bias_output)


Final Weights (Input to Hidden):
[[3.77876719 5.77131988]
 [3.78345326 5.79331783]]
Final Bias (Hidden):
[[-5.79319383 -2.42207539]]
Final Weights (Hidden to Output):
[[-8.17262084]
 [ 7.55637468]]
Final Bias (Output):
[[-3.41823076]]
